# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: alikehel
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Cairo
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 2
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_url: https://wakatime.com/
          plugin_wakatime_user: alikehel
          plugin_leetcode: yes
          plugin_leetcode_sections: solved
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: watching, characters
          plugin_anilist_limit: 10
          plugin_anilist_limit_characters: 11
